/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.database.Database;
import java.awt.event.KeyEvent;
import java.sql.SQLException;

/**
 *Object for creating login window
 * @author jakubwawak
 */
public class GUI_login_window extends javax.swing.JFrame {

    /**
     * Creates new form GUI_login_window
     */
    Database database;
    
    public GUI_login_window(Database database) {
        this.database = database;
        initComponents();
        this.setLocationRelativeTo(null);
        label_version.setText(database.program_version);
        label_build.setText(database.program_build);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        field_login = new javax.swing.JTextField();
        field_password = new javax.swing.JPasswordField();
        button_login = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        button_register = new javax.swing.JButton();
        label_version = new javax.swing.JLabel();
        label_build = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in to Tick2");

        jLabel1.setFont(new java.awt.Font("Baskerville", 0, 130)); // NOI18N
        jLabel1.setText("T");

        field_login.setText("login");

        field_password.setText("jPasswordField1");
        field_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_passwordFocusGained(evt);
            }
        });
        field_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_passwordKeyPressed(evt);
            }
        });

        button_login.setText("Log in");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        button_register.setText("Register");
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        label_version.setText("jLabel2");

        label_build.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_build, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_register, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(field_login)
                            .addComponent(field_password)
                            .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(label_version)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addComponent(label_build))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cancel)
                    .addComponent(button_register))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(label_version))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_passwordFocusGained
        field_password.setText("");
    }//GEN-LAST:event_field_passwordFocusGained

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        if( !field_password.getText().isEmpty() && !field_login.getText().isEmpty()){
            try {
                // login attempt
                database.logged = database.user_login(field_login.getText(), field_password.getText());
                if ( database.logged != null ){
                    new GUI_main_window(database);
                    dispose();
                }
                else{
                    new message_window(this,true,"Wrong login data. User not found");
                }
            } catch (SQLException ex) {
                new message_window(this,true,"Error: "+ex.toString());
            }
        }
        else{
            new message_window(this,true,"Wrong input, please try again");
        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        new GUI_register_window(this,true,database);
    }//GEN-LAST:event_button_registerActionPerformed

    private void field_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_passwordKeyPressed
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER ){
            if( !field_password.getText().isEmpty() && !field_login.getText().isEmpty()){
                try {
                    // login attempt
                    database.logged = database.user_login(field_login.getText(), field_password.getText());
                    if ( database.logged != null ){
                        new GUI_main_window(database);
                        dispose();
                    }
                    else{
                        new message_window(this,true,"Wrong login data. User not found");
                    }
                } catch (SQLException ex) {
                    new message_window(this,true,"Error: "+ex.toString());
                }
            }
            else{
                new message_window(this,true,"Wrong input, please try again");
            }
        }
    }//GEN-LAST:event_field_passwordKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_login;
    private javax.swing.JButton button_register;
    private javax.swing.JTextField field_login;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_build;
    private javax.swing.JLabel label_version;
    // End of variables declaration//GEN-END:variables
}
