/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.database.Database;
import com.jakubwawak.tick2.Configuration;
import com.jakubwawak.tick2.Options;
import java.io.IOException;
import java.sql.SQLException;

/**
 *Function for creating window for options
 * @author jakubwawak
 */
public class GUI_options_window extends javax.swing.JDialog {

    /**
     * Creates new form GUI_options_window
     */
    Options options;
    Database database;
    
    public GUI_options_window(java.awt.Frame parent, boolean modal,Database database,Options options) {
        super(parent, modal);
        this.options = options;
        this.database = database;
        initComponents();
        this.setLocationRelativeTo(null);
        load_window();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        checkbox_debug = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        combobox_welcome = new javax.swing.JComboBox<>();
        checkbox_fastlogin = new javax.swing.JCheckBox();
        checkbox_autocheck = new javax.swing.JCheckBox();
        combobox_gui = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");

        jButton1.setText("Reset password");

        jLabel1.setText("Number of entries:");

        checkbox_debug.setText("Debug - if checked log is saved to file");

        jButton2.setText("Database connection data");

        combobox_welcome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blank", "Scenes", "Ticks", "Lists", " " }));
        combobox_welcome.setToolTipText("Welcome screen setup");

        checkbox_fastlogin.setText("Fast log in - saves login for faster access ");

        checkbox_autocheck.setText("Auto check - auto check new shares on startup");

        combobox_gui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GUI - Graphical User Interface", "CUI - Console User Interface" }));
        combobox_gui.setToolTipText("Setting for choosing interfaces");

        jButton3.setText("Set configuration file to default");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combobox_welcome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combobox_gui, 0, 341, Short.MAX_VALUE)
                    .addComponent(checkbox_autocheck)
                    .addComponent(checkbox_fastlogin)
                    .addComponent(jLabel1)
                    .addComponent(checkbox_debug)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkbox_debug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkbox_fastlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkbox_autocheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combobox_gui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combobox_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Function for preparing components
     */
    void load_window(){
        if (options.debug == 1 ){
            checkbox_debug.setSelected(true);
        }
        if ( options.auto_login.equals("blank") ){
            checkbox_fastlogin.setSelected(true);
        }
        if ( options.auto_shares == 1){
            checkbox_autocheck.setSelected(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox checkbox_autocheck;
    public javax.swing.JCheckBox checkbox_debug;
    public javax.swing.JCheckBox checkbox_fastlogin;
    public javax.swing.JComboBox<String> combobox_gui;
    public javax.swing.JComboBox<String> combobox_welcome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
