/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.database.Database;
import com.jakubwawak.database.Database_ComponentFiller;
import com.jakubwawak.database.Database_Garbage_Collector;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Function for creating GUI window for adding data ( universal )
 * @author jakubwawak
 */
public class GUI_dataadd_universal_window extends javax.swing.JDialog {

    /**
     * Creates new form GUI_dataadd_universal_window
     * modes:
     * category
     * place
     * hashtag table
     */
    Database database;
    Database_ComponentFiller dcf;
    String mode;
    String selected_data;
    String table_name, table_object_name;
    int obj_index; 
    
    /**
     * Main constructor
     * @param parent
     * @param modal
     * @param database
     * @param mode
     * @throws SQLException 
     */
    public GUI_dataadd_universal_window(javax.swing.JDialog parent, boolean modal,Database database,String mode) throws SQLException {
        super(parent, modal);
        
        this.database = database;
        this.mode = mode;
        dcf = new Database_ComponentFiller(this.database);
        selected_data = "";
        obj_index = -1;
        initComponents();
        
        load_components();
        label_deleted.setVisible(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    /**
     * Function for setting response on components
     * @param mode 
     * modes:
     * 1 - done 
     * 0 - not done
     */
    void set_components_(int mode) throws SQLException{
        if ( mode == 1){
            label_deleted.setVisible(true);
            load_components();
        }
        else if ( mode == 0){
            label_deleted.setText("Failed");
            load_components();
        }
    }
    
    /**
     * Function for loading data into components  
     * @throws SQLException 
     */
    void load_components() throws SQLException{
        String label_text = "";
        jlist_data.setModel(dcf.translator(dcf.datagather_simpleview(mode)));
        label_canteditdefaults.setVisible(false);
        jLabel1.setText(label_text);
        
        if ( mode.equals("category") ){
            table_name = "CATEGORY";
            table_object_name = "category_id";
        }
        else if ( mode.equals("place")){
            table_name = "PLACE";
            table_object_name = "place_id";
        }
        else if ( mode.equals("hashtag table")){
            table_name = "HASHTAG_TABLE";
            table_object_name = "hashtag_table_id";
        }
        else if ( mode.equals("tag")){
            table_name = "TAG";
            table_object_name = "tag_id";
        }
        else{
            table_name = "";
            table_object_name = "";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_data = new javax.swing.JList<>();
        button_add = new javax.swing.JButton();
        button_edit = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_deleted = new javax.swing.JLabel();
        label_canteditdefaults = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlist_data.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlist_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlist_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlist_data);

        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_edit.setText("Edit");
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        label_deleted.setText("Deleted");

        label_canteditdefaults.setText("You can't edit defaults.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_canteditdefaults)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_deleted)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_edit)
                    .addComponent(button_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_deleted)
                    .addComponent(label_canteditdefaults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlist_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlist_dataMouseClicked
        label_canteditdefaults.setVisible(false);
        selected_data = jlist_data.getSelectedValue();
        obj_index = Integer.parseInt(selected_data.split(":")[0]);
        label_deleted.setVisible(false);
    }//GEN-LAST:event_jlist_dataMouseClicked

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        try {
            new GUI_datainput_universal_window(this,true,database,mode,1);
        } catch (SQLException ex) {
            new message_window_jdialog(this,true,"Error: "+ex.toString());
        }
        try {
            load_components();
        } catch (SQLException ex) {
            new message_window_jdialog(this,true,"Error: "+ex.toString());
        }
    }//GEN-LAST:event_button_addActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        if ( !selected_data.equals("") || jlist_data.getSelectedValue() != null){
            database.log.add("Deleting data: "+selected_data+ ", obj_index: "+Integer.toString(obj_index),"GUI_dataadd_universal_window");
            Database_Garbage_Collector dgc = new Database_Garbage_Collector(database);
            if ( obj_index!= -1){
                try {
                    if (dgc.sec_check(obj_index, table_object_name, table_name) == 1){
                            dgc.delete(obj_index, table_object_name, table_name);
                            set_components_(1);
                        }
                    else{
                            set_components_(0);
                    }
                    
                } catch (SQLException ex) {
                    new message_window_jdialog(this,true,"Error: "+ex.toString());
                }
            }
            else{
                try {
                    set_components_(0);
                } catch (SQLException ex) {
                    new message_window_jdialog(this,true,"Error: "+ex.toString());
                }
            }
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editActionPerformed
        try {
            if ( obj_index == 1){
                label_canteditdefaults.setVisible(true);
            }
            else{
                database.log.add("Loading window to edit, mode: "+mode+ ", obj_index: "+Integer.toString(obj_index),"GUI_dataadd_universal_window");
                new GUI_datainput_universal_window(this,true,database,mode,obj_index);
                set_components_(0);
            }
        } catch (SQLException ex) {
            new message_window_jdialog(this,true,"Error: "+ex.toString());
        }
    }//GEN-LAST:event_button_editActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlist_data;
    private javax.swing.JLabel label_canteditdefaults;
    private javax.swing.JLabel label_deleted;
    // End of variables declaration//GEN-END:variables
}
