/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.gui;

import com.jakubwawak.database.Database;
import com.jakubwawak.tick2.Tick_User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author jakubwawak
 */
public class GUI_register_window extends javax.swing.JDialog {

    /**
     * Creates new form GUI_register_window
     */
    Tick_User new_user;
    Database database;
    
    public GUI_register_window(java.awt.Frame parent, boolean modal,Database database) {
        super(parent, modal);
        this.database = database;
        new_user  = new Tick_User();
        this.setLocationRelativeTo(parent);
        new_user = new Tick_User();
        initComponents();
        load_window();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_name = new javax.swing.JTextField();
        field_surname = new javax.swing.JTextField();
        field_login = new javax.swing.JTextField();
        field_email = new javax.swing.JTextField();
        field_password = new javax.swing.JPasswordField();
        field_passwordre = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_register = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        combobox_age = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");

        field_name.setText("name");
        field_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_nameFocusGained(evt);
            }
        });

        field_surname.setText("surname");
        field_surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_surnameFocusGained(evt);
            }
        });

        field_login.setText("login");
        field_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_loginFocusLost(evt);
            }
        });

        field_email.setText("e-mail");
        field_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_emailFocusGained(evt);
            }
        });

        field_password.setText("password");
        field_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_passwordFocusGained(evt);
            }
        });

        field_passwordre.setText("jPasswordField1");
        field_passwordre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                field_passwordreFocusGained(evt);
            }
        });

        jLabel1.setText("Password:");

        jLabel2.setText("Re-enter password:");

        jLabel3.setFont(new java.awt.Font("Baskerville", 0, 48)); // NOI18N
        jLabel3.setText("Register");

        button_register.setText("Register");
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        jLabel4.setText("Age:");

        combobox_age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(field_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(field_email, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(field_passwordre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(combobox_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combobox_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_passwordre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Function for setting components
     */
    void load_window(){
        field_login.setText("login");
    }
    
    /**
     * Function for checking if password match
     * @return boolean
     */
    boolean password_match(){
        return field_password.getText().equals(field_passwordre.getText());
    }
    
    /**
     * Function for checking if password is set to default
     * @return boolean
     */
    boolean password_default(){
        return field_password.getPassword().equals("password") 
                || field_passwordre.getPassword().equals("password");
    }
    
    /**
     * Function for field validation
     * @param field
     * @return boolean
     */
    boolean validate_field(JTextField field){
        if (field == field_login){
            return !field.getText().equals("login") && !field.getText().equals("");
        }
        else if ( field == field_name){
            return !field.getText().equals("name") && !field.getText().equals("");
        }
        else if ( field == field_surname){
            return !field.getText().equals("surname") && !field.getText().equals("");
        }
        else if ( field == field_email){
            return !field.getText().equals("e-mail") && !field.getText().equals("");
        }
        else{
            return !field.getText().equals("");
        }
    }
    /**
     * Function for field validation
     * @return boolean
     */
    boolean validate_fields(){
        return validate_field(field_name) && validate_field(field_surname)
                && validate_field(field_email) && validate_field(field_name);
    }
    
    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_button_cancelActionPerformed

    private void field_surnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_surnameFocusGained
        if(database.check_login_availability(field_login.getText())){
            field_login.setText("Login taken!");
        }
        if ( field_surname.getText().equals("surname"))
            field_surname.setText("");
        if ( field_surname.getText().isEmpty())
            field_surname.setText("surname");
    }//GEN-LAST:event_field_surnameFocusGained

    private void field_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_loginFocusGained
        if(database.check_login_availability(field_login.getText())){
            field_login.setText("Login taken!");
        }
        if ( field_login.getText().equals("login"))
            field_login.setText("");
        if (field_login.getText().isEmpty()){
            field_login.setText("login");
        }
        
    }//GEN-LAST:event_field_loginFocusGained

    private void field_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_emailFocusGained
        if(database.check_login_availability(field_login.getText())){
            field_login.setText("Login taken!");
        }
        if (field_email.getText().equals("e-mail"))
            field_email.setText("");
        if (field_email.getText().isEmpty())
            field_email.setText("e-mail");
    }//GEN-LAST:event_field_emailFocusGained

    private void field_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_loginFocusLost
        if(database.check_login_availability(field_login.getText())){
            field_login.setText("Login taken!");
        }
    }//GEN-LAST:event_field_loginFocusLost

    private void field_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_nameFocusGained
        
        if(database.check_login_availability(field_login.getText())){
            field_login.setText("Login taken!");
        }
        
        if ( field_name.getText().isEmpty())
            field_name.setText("name");
    }//GEN-LAST:event_field_nameFocusGained

    private void field_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_passwordFocusGained
        if (field_password.getPassword().equals("password"))
            field_password.setText("");
    }//GEN-LAST:event_field_passwordFocusGained

    private void field_passwordreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_passwordreFocusGained
        if ( field_passwordre.getPassword().equals("password"))
            field_password.setText("");
    }//GEN-LAST:event_field_passwordreFocusGained

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        if ( !database.check_login_availability(field_login.getText()) ){
            if ( password_match() ){
                if ( !password_default() ){
                    if ( validate_fields() ){
                        // ready to save data to object
                        new_user.owner_login = field_login.getText();
                        new_user.owner_name = field_name.getText();
                        new_user.owner_email_address = field_email.getText();
                        new_user.owner_age = Integer.parseInt(combobox_age.getSelectedItem().toString());
                        new_user.put_surname(field_surname.getText());
                        new_user.put_password(String.valueOf(field_passwordre.getPassword()));
                        new_user.put_elements(new_user.wall_updater());
                        try {
                            database.register_user(new_user);
                            new message_window_jdialog(this,true,"Registered successfully");
                            dispose();
                        } catch (SQLException ex) {
                            new message_window_jdialog(this,true,"Error: "+ex.toString());
                        }
                    }
                    else{
                        new message_window_jdialog(this,true,"Failed. Check all fields");
                    }
                }
                else{
                    new message_window_jdialog(this,true,"Failed. Password is set to default");
                    field_password.setText("password");
                    field_passwordre.setText("password");
                }
            }
            else{
                new message_window_jdialog(this,true,"Failed. Passwords didn't match");
                field_password.setText("password");
                field_passwordre.setText("password");
            }
        }
        else{
            new message_window_jdialog(this,true,"Failed. Login taken");
        }
    }//GEN-LAST:event_button_registerActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_register;
    private javax.swing.JComboBox<String> combobox_age;
    private javax.swing.JTextField field_email;
    private javax.swing.JTextField field_login;
    private javax.swing.JTextField field_name;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JPasswordField field_passwordre;
    private javax.swing.JTextField field_surname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
